config/routes.rb
Rails.application.routes.draw do
  resources :user_events
  resources :events
  resources :users
  resources :time_intervals
  resources :locations
  resources :categories
  resources :cities

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "login", to: "sessions#destroy"
  get "/", to: redirect("/login")

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :locations
  has_many :events
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :events
  has_many :locations

  def name_state
    "#{self.name}, #{self.state}"
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :city
  belongs_to :location
  belongs_to :category
  belongs_to :time_interval
  has_many :user_events
  has_many :users, through: :user_events
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :city
  belongs_to :category
  has_many :events

  def name_city
    "#{self.name}, located in #{self.city.name_state}"
  end
end

app/models/time_interval.rb
class TimeInterval < ApplicationRecord
  has_many :events
  
  def to_event_time(time)
    time + 60*self.interval 
  end

  def self.format_time(time)
    time.strftime("%I:%M %p")
  end

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :user_events
  has_many :events, through: :user_events
  has_secure_password
  
  validates :username, presence: true, uniqueness: true
  validates :password, length: { in: 4..20 }

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def formatted_phone_number
    self.phone_number.insert(3, "-").insert(7, "-")
  end

  def total_attended
    self.events.count
  end

  def total_joined
    self.events.select do |event|
      event.users.first != self
    end.count
  end

  def total_coordinated
    self.events.select do |event|
      event.users.first == self
    end.count
  end

  def total_participants
    total_participants = self.events.reduce(0) do |sum, event|
      sum + event.users.count
    end
  end

  def average_number_of_participants
    (total_participants / total_attended.to_f)
  end

  def last_event
    last_event = nil
    last_attended = nil

    self.events.each do |event|
      if(!last_attended || last_attended < event.event_time.to_time)
        last_attended = event.event_time.to_time
        last_event = event
      end
    end
    last_event
  end

  def average_time_interval
    count = 0
    sum_of_interval = 0
  
    self.events.each do |event|
      sum_of_interval += event.time_interval.interval.to_i
      count += 1
    end
    sum_of_interval/count.to_f
  end

  def upcoming_events
    self.user_events.select {|user_event| user_event.event.event_time.to_time >= Time.now}.count
  end

end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_user

  def get_user
    if (session[:user_id])
      @user = User.find(session[:user_id])
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all 
  end 

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  
  def index
    @cities = City.all
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all.select do |x|
      x.event_time.to_time > Time.now && x.city == @user.city
    end
    @scheduled_user_events = Event.all.select do |x|
      (x.event_time.to_time > Time.now && x.city == @user.city) && (x.users.include?(@user))
    end
    @unattended_events = @events.count - @scheduled_user_events.count
  end

  def show
    @event = Event.find(params[:id])
    @user_event = UserEvent.new
    @coordinator = @event.users.first
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(allowed_params)
    @event.event_time = @event.time_interval.to_event_time(Time.now)
    @event.city = @user.city
    @event.save
    UserEvent.create(user: @user, event: @event)
    redirect_to events_path
  end

  private

  def allowed_params
    params.require(:event).permit(:location_id, :category_id, :time_interval_id, :name, :notes)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new

    render "login/login"
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if (@user && @user.authenticate(params[:user][:password]))
      session[:user_id] = @user.id
      redirect_to events_path
    else
      @user = User.new
      @error = "Incorrect login, please try again"
      render "login/login"
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_params)
    if @user.valid?
      @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    # use below methods, rather than .update because of password validation
    @user.assign_attributes(allowed_update_params)
    @user.save(validate: false)
    redirect_to user_path(@user)
  end


  private

  def allowed_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :username, :password, :city_id)
  end 

  def allowed_update_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :city_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/time_intervals_helper.rb
module TimeIntervalsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>All categories</h1>
<ul><% @categories.each do |category| %>
  <li><%= category.name %></li>
  <% end %>
</ul>

app/views/cities/index.html.erb
<h1>Current cities</h1>
<ul><% @cities.each do |city| %>
  <li><%= city.name_state %></li>
  <% end %>
</ul>

app/views/events/index.html.erb
<h1>Welcome, <%= @user.full_name %>!</h1>
<br>
<br>
<% if @user.user_events.count > 0 %>
  <% unless @user.user_events.last.event.event_time.to_time < Time.now %>
    <% if @user.upcoming_events == 1 %>
      <h3>You're attending this event:</h3><br>
    <% elsif @user.upcoming_events > 1 %>
      <h3>You're attending <%= @user.upcoming_events %> events:</h3><br>
    <% end %>
  <% end %>
  <% @user.user_events.each do |user_event| %>
    <% if user_event.event.event_time.to_time > Time.now && user_event.event.city == @user.city %>
      <h3><%= link_to "#{user_event.event.name.upcase}     #{TimeInterval.format_time(user_event.event.event_time.to_time)}", user_event_path(user_event) %></h3>
      <h4>@ <%= user_event.event.location.name %></h4><br>
      <br>
      <br>
    <% end %>
  <% end %>
<% end %>

<% if @unattended_events == 1 && @user.upcoming_events > 0 %>
  <h3>There's currently <%= @unattended_events %> other event in <%= @user.city.name_state %></h3>
<% elsif @unattended_events ==1 && @user.upcoming_events == 0 %>
  <h3>There's currently <%= @unattended_events %> event in <%= @user.city.name_state %></h3>
<% elsif @unattended_events > 0 && @user.upcoming_events > 0 %>
  <h3>There are currently <%= @unattended_events %> other events in <%= @user.city.name_state %></h3>
<% elsif @unattended_events > 0 && @user.upcoming_events == 0 %>
  <h3>There are currently <%= @unattended_events %> events in <%= @user.city.name_state %></h3>
<% end %>
<ul>
<% @events.each do |event| %>
  <% if !event.users.ids.include?(@user.id) %>
    <li><%=link_to "#{event.name.capitalize} @ #{event.location.name} #{TimeInterval.format_time(event.event_time.to_time)}", event_path(event) %> 
  <% end %>
<% end %>
<br>
<br>
</ul>
<li style="list-style-type: none"><%= link_to "Create Event", new_event_path, class: "btn btn-primary"%></li>
</ul>

app/views/events/new.html.erb
<h2>Hi <%= @user.first_name %>,</h2>
<p>Use the form below to create a new event in <%= @user.city.name_state %></p>
<%= form_for @event do |f| %>

  <div class="field form-group row col-md-4">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %><br>
  </div>

<div class="form-row">

  <div class="field form-group col-auto">
    <%= f.label "Minutes till"%><br>
    <%= f.collection_select :time_interval_id, TimeInterval.all, :id, :interval, prompt: true,  class: "form-control" %><br>
  </div>

  <div class="field form-group col-auto">
    <%= f.label :location %><br>
    <%= f.collection_select :location_id, @user.city.locations, :id, :name, prompt: true,  class: "form-control" %><br>
  </div>

  <div class="field form-group col-auto">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true,  class: "form-control" %><br>
  </div>

</div>

  <div class="field form-group row col-md-4">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control" %><br>
  </div>

    <%= f.submit "Create event", class: "btn btn-success"%>
<% end %>
<br>
<%= link_to "Back to #{@user.city.name_state} events", events_path %>

app/views/events/show.html.erb
<h3>Category: <%= @event.category.name %></h3>
<h1><%= @event.name.upcase %>     <%=TimeInterval.format_time(@event.event_time.to_time) %></h1>
<h2>@ <%= @event.location.name %></h2>
<% if @coordinator %>
  <p>Coordinator: <%= @coordinator.first_name %> </p><br>
<% end %>
<h2>Notes: </h2>
<p><%= @event.notes %></p>

<%= form_for @user_event do |f| %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :event_id, value: @event.id %>
  <%= f.submit "Join event", class: "btn btn-success" %>
<% end %>
<br>
<%= link_to "Back to #{@user.city.name_state} events", events_path %>

app/views/locations/index.html.erb
<h1>All Locations</h1>
<ul><% @locations.each do |location| %>
  <li>
  <%= location.name_city%><br>
  Category: <%= location.category.name %>
  </li>
  
<% end %></ul>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>

  <div class="field form-group row col-md-4">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control" %><br>
  </div>
  <div class="field form-group row col-md-4">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %><br>
  </div>
  <div class="row">
    <div class="field form-group col-md-4">
      <%= f.label :city %><br>
      <%= f.collection_select :city_id, City.all, :id, :name_state, prompt:true%><br>
    </div>
  </div>
  <div class="field form-group row col-md-4">
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number, class: "form-control"%><br>
  </div>
  <br>

    <%= f.submit "Update", class: "btn btn-success"%>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
  <li><%= user.full_name %> from <%= user.city.name_state %><br>
  Username: <%= user.username %><br>
  Phone number: <%= user.formatted_phone_number %></li><br>
  <% end %>
</ul>

app/views/users/new.html.erb
<nav>
  <%= link_to "Login", login_path %>
</nav>

<%= form_for @user do |f| %>

  <div class="field form-group row col-md-4">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control" %><br>
  </div>
  <div class="field form-group row col-md-4">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %><br>
  </div>
  <div class="row">
    <div class="field form-group col-md-4">
      <%= f.label :city %><br>
      <%= f.collection_select :city_id, City.all, :id, :name_state, prompt:true%><br>
    </div>
  </div>
  <div class="field form-group row col-md-4">
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number, class: "form-control"%><br>
  </div>
  
  <br>
  <br>
  <div class="field form-group row col-md-3">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: "form-control" %><br>
  </div>
  <div class="field form-group row col-md-3">
    <%= f.label :password %><br>
    <%= f.password_field :password, class: "form-control" %><br>
  </div>
  <br>
  <%= f.submit "Create account", class: "btn btn-success"%>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h3>First name: <%= @user.first_name %></h3>
<h3>Last name: <%= @user.last_name %></h3>
<h3>Location: <%= @user.city.name_state %></h3>
<h3>Phone: <%= @user.formatted_phone_number %></h3><br>

<%= link_to "Back to #{@user.city.name_state} events", events_path %>
<br>
<br>
<% if @user.last_event %>

<h2>Your stats:</h2><br>

<h3>"<%= @user.last_event.name %>" was the last event you participated in</h3>
<br>
<h3>You've been a part of <%= @user.total_attended %> event(s) </h3>
<ul>
<li><h5>you coordinated <%= @user.total_coordinated %> of them</h5></li>
<li><h5>you joined <%= @user.total_joined %> of these</h5></li>
</ul>
<h3>Here's a list of those events</h3>
<ul><% @user.events.each do |event| %>
  <li><h5><%= event.name %> <%= event.created_at.strftime("%m/%d/%Y")%></h5>
      <% if event.users.count > 1%>
        <p><%= event.users.count %> people attended</p></li>
      <% else %>
        <p><%= event.users.count %> person attended</p></li>
      <% end %>
    <% end %>
</ul>
<h3>That's an average of <%= @user.average_number_of_participants %> people per event </h3>
<h3>You typically participate in events that occur within <%= @user.average_time_interval %> minutes of having been created</h3>
<% end %>
<br>
<br>
<%= link_to "Update info", edit_user_path(@user), class: "btn btn-primary btn-sm" %>
<br>
<br>